### ISSUE TITLE
Withdraw does not seem to work

### ISSUE THREAD

**Issue by forReason** [burakoner/OKX.Api#10]
I am trying to withdraw to a trusted address. The OkxWithdrawalResponse says ok, no error. However, the balance does not show up in my account ahd the balance does not change.

I have verified the withdrawal works manually on the webpage.
```
RestCallResult<OkxWithdrawalResponse> withdrawResult = API.RestClient.Funding.WithdrawAsync(
    currency: withdrawCurrency.CurrencyString,
    amount: (decimal)amount - 0.0001m,
    destination: withdrawType,
    toAddress: adress,
    fee: (decimal)withdrawalChain.FeeMin,
```

**Comment by burakoner** [comment]
I've just tested for you and it worked perfect for me

```csharp
var api = new OKX.Api.OKXRestApiClient(new OKX.Api.OKXRestApiClientOptions
{
    ApiCredentials = new OkxApiCredentials("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"),
});
var withdrawal = await api.Funding.WithdrawAsync(
"USDT", 100.0m, OkxWithdrawalDestination.DigitalCurrencyAddress,
"TXwqoD7doMESgitfWa8B2gHL7HuweMmNBJ",
1.0m, "USDT-TRC20");
`

**Comment by forReason** [comment]
I think this information should be correct

Response from server to request currency information:
![image](https://github.com/burakoner/OKX.Api/assets/12736950/edca00cf-521f-4327-9566-c27f26323797)
```
RestCallResult<OkxWithdrawalResponse> withdrawResult = API.RestClient.Funding.WithdrawAsync(
    currency: "XCH",
    amount: (decimal)amount - 0.0001m,
    destination: OkxWithdrawalDestination.DigitalCurrencyAddress,
    toAddress: adress,
    fee: 0.0004m,
    chain: "XCH-Chia"
).Result;
```

```
"{\"amt\":\"2.067811\",\"ccy\":\"XCH\",\"chain\":\"XCH-Chia\",\"dest\":\"4\",\"fee\":\"0.0004\",\"toAddr\":\"xch1j494xxyt93gj0s2adshgcftr5zlmtrzhwqkvkjgfmryxzyk3hyrqfgu9sa\"}"
```

I cant really fiind anything incorrect.
I tried manually changing the chain for instance, which leads to a server 400 error. However for my request it returns success.

![image](https://github.com/burakoner/OKX.Api/assets/12736950/8900ebf5-3093-4249-8384-1ad8b8e802ed)

anything else I can debug or do you know how to reach outd to okx api support?
They dont really seem to have any support, which is concerning

**Comment by burakoner** [comment]
You can try with raw data option as below.

var api = new OKX.Api.OKXRestApiClient(new OKX.Api.OKXRestApiClientOptions
{
    ApiCredentials = new OkxApiCredentials("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"),
    **RawResponse = true**
});

This'll fill Raw property in result with OKX response

**Comment by burakoner** [comment]
OK. I'm happy to help you.
By the way we experienced that OKX.Api cant catch some errors. I'll work on this issue as well.

**Comment by forReason** [comment]
The raw property helps a lot perhaps this could be included into the responses per default.
Feel free to close the issue or keep it open as a reference if you want to work on it. For me its good now.

**Comment by burakoner** [comment]
Thank you for your feedback. Have a nice day
