### ISSUE TITLE
Cancel open order on spot doesnt work

### ISSUE THREAD

**Issue by kayahasa** [burakoner/OKX.Api#13]
Cancel order doesnt work response is order not found. But the orderId is correct

**Comment by kayahasa** [comment]
I have realized that, somehow the orderId is being changed after serializing it to the frontend. The last three digits are changing. 

Now i am trying to find a solution to that. But be aware that, when we fetch open orders and lets say the orderId is:

588591686646136846

After serialization to the frontend, it is becoming to:
588591686646136800

Somehow it is rounding but i dont know why. Thats why, the cancel order response was 'Order not found'.

Note: This stuation is not related to this library.

**Comment by burakoner** [comment]
I'll inspect deeply

**Comment by burakoner** [comment]
Which library do you use?

**Comment by kayahasa** [comment]
It is related to javascript. Even in Swagger, it is changing. Javascript cannot handle such big numbers.

I have converted it into string and problem fixed

**Comment by burakoner** [comment]
I'm happy for you. Have a nice day.
