### ISSUE TITLE
PlaceOrderAsync，Prompt for unauthorized

### ISSUE THREAD

**Issue by 372364996** [burakoner/OKX.Api#17]
`
var api = new OKXRestApiClient();
                api.SetApiCredentials(APIKEY, APISECRET, APIPASSPHRASE);
                var trade_01 = await api.Trade.PlaceOrderAsync("ETH-USDT-SWAP", OkxTradeMode.Cross, OkxOrderSide.Buy, OkxPositionSide.Long, OkxOrderType.MarketOrder, 10m);
`
Prompt for unauthorized

It can ensure that APIKEY, APISECRET, and APIPASSPHRASE are correct

**Comment by lrlr90** [comment]
api.Trade.ClientOptions.ApiCredentials= new OkxApiCredentials(Apikey, Apisecret,APIPASSPHRASE ); 你试试。我之前在ws遇到过。

**Comment by burakoner** [comment]
I think you solved problem
