### ISSUE TITLE
Subscribing to websocket API does not work after recent OKX API update

### ISSUE THREAD

**Issue by Radimersky** [burakoner/OKX.Api#18]
Based on this article https://www.okx.com/help-center/changes-to-v5-api-websocket-subscription-parameter-and-url
subscribing to websocket API now requires "instFamily" parameter instead of "uly". 

Please adjust the app according to this update.

**Comment by burakoner** [comment]
I've added this issue to my urgent program

**Comment by burakoner** [comment]
Fixed in version 1.1.6 https://github.com/burakoner/OKX.Api/commit/efb456881f483f5b2012a694ede8768755e2df44 https://www.nuget.org/packages/OKX.Api/1.1.6
