### ISSUE TITLE
PlaceOrder error

### ISSUE THREAD

**Issue by xiuxiang** [burakoner/OKX.Api#19]
api.SetApiCredentials has been set correctly
var trade_01 = api.PlaceOrder("BTC-USDT", OkexTradeMode.Cash, OkexOrderSide.Buy, OkexPositionSide.Long, OkexOrderType.MarketOrder, 0.01m);
Error : 1: All operations failed
There is no specific error message, I don't know how to deal with it

**Comment by burakoner** [comment]
Sorry for delay, I was on vacation. You can track original response with RawResponse as below.

```csharp
var api = new OKXRestApiClient(new OKXRestApiClientOptions
{
    RawResponse = true,
});

var call = await api.SomeMethodToCall();
var rawResponse = call.Raw;
```

**Comment by mesutpiskin** [comment]
Hello, I am encountering a similar error. The Response object appears to be empty, what could be the reason for this, do you have any information on this subject? 
Thank you.

var trade_01 = await api.OrderBookTrading.Trade.PlaceOrderAsync("BTC-USDT",
    OkxTradeMode.Cash, OkxOrderSide.Buy, OkxPositionSide.Long, OkxOrderType.MarketOrder, 0.1m);

![image](https://github.com/burakoner/OKX.Api/assets/3519662/5b52d9d5-bab8-4024-bd30-e42e5da3289b)

**Comment by mesutpiskin** [comment]
> Hello, I am encountering a similar error. The Response object appears to be empty, what could be the reason for this, do you have any information on this case? Thanks for assist
> 
> var trade_01 = await api.OrderBookTrading.Trade.PlaceOrderAsync("BTC-USDT", OkxTradeMode.Cash, OkxOrderSide.Buy, OkxPositionSide.Long, OkxOrderType.MarketOrder, 0.1m);
> 
> ![image](https://private-user-images.githubusercontent.com/3519662/308190296-5b52d9d5-bab8-4024-bd30-e42e5da3289b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDQxNTUsIm5iZiI6MTcwOTA0Mzg1NSwicGF0aCI6Ii8zNTE5NjYyLzMwODE5MDI5Ni01YjUyZDlkNS1iYWI4LTQwMjQtYmQzMC1lNDJlNWRhMzI4OWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMTQyNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTY0MjRmM2YzNGI4YmE4NGFlMmZhYmY5ZGQyZTUyMGJlY2E2NWJlOGFmODRhYTlkNzRkZTcxYzg1YWRmNWE0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p-LR_xzl_v8Dt_I-8SjEwsp_8jikdUrDpLmY06npzyE)

When I sent a request with Postman, I received a response like below, the reason for the error is due to insufficient balance, but the error message returned in the data is not being handled, I guess an improvement is needed here.

service response:

```JSON
{
    "code": "1",
    "data": [
        {
            "clOrdId": "b15",
            "ordId": "",
            "sCode": "51008",
            "sMsg": "Order failed. Insufficient USDT balance in account. ",
            "tag": ""
        }
    ],
    "inTime": "1709043826429122",
    "msg": "All operations failed",
    "outTime": "1709043826429623"
}
```
