### ISSUE TITLE
Incompelte return from SendOKXSingleRequest() and SendOKXRequest()

### ISSUE THREAD

**Issue by alekved** [burakoner/OKX.Api#2]
Class OKXBaseRestApiClient, functions mentioned in the issue title.
If the web request succeeds, i.e. result.Success == true for SendRequestAsync(), but there is an exchange error, i.e. result.Data.ErrorCode > 0, then no additional information about the error is returned to the caller.
For example, if I try to send an order with an amount exceeding the limit, I only get ErrorCode = 1, Message = "All operations failed".
Meanwhile, the result.Data.Data[0] contains additional information like
{"ordId":null,"clOrdId":"","tag":"538a3965e538BCDE","sCode":"51201","sMsg":"Value of per market order cannot exceed 1,000,000 USDT "}
which is not passed to the caller.

**Comment by burakoner** [comment]
OKX returns two main types of responses. One is a single data object, one is an array. OKX also returns errorcode in some responses (e.g placing canceling orders), and also OKX returns a master error code. So yes you're right, there is a problem here. I agree with you about inner error codes are more important than the master one. So I've made some changes in code. I'll release it at this evening. You'll see inner error codes in some endpoints. Thanks for feedback

**Comment by burakoner** [comment]
New Release https://github.com/burakoner/OKX.Api/commit/da27018a20640b5e5ba2186311d54b3359569355 and https://www.nuget.org/packages/OKX.Api/1.0.3
