### ISSUE TITLE
Bug: Debugging Symbols are not included in the nuget package

### ISSUE THREAD

**Issue by forReason** [burakoner/OKX.Api#22]
It is such a pity. I have seen that you have written beautiful xml comments documenting the code.
However:
![image](https://github.com/burakoner/OKX.Api/assets/12736950/6e64a82f-f478-472d-be0b-6511243ab5bd)

the documentation does not apply to the nuget package.

please assure the following settings are set if you use visual studio:
1. right click on the project in the solution explorer:
2. choose `Properties`
3. ensure the following are set:
Build > General > Debug Symbols > Embedded in dll/exe, portable across plattforms
![image](https://github.com/burakoner/OKX.Api/assets/12736950/efdc201a-e342-496e-9092-f50e933f7b6d)
Build > Output > Documentation file
![image](https://github.com/burakoner/OKX.Api/assets/12736950/b67d5d98-6824-453e-b826-926267d13bbc)

Thank you very much for the library

**Comment by burakoner** [comment]
Thank you for your feedback. I'll add documentation on next release

**Comment by burakoner** [comment]
Version 1.2.0 released
