### ISSUE TITLE
GetInstrumentsAsync Error

### ISSUE THREAD

**Issue by overstartup** [burakoner/OKX.Api#3]
It seems this method doesn't work. And even it doesn't return values when I set other parameters.

```
 api.MarketData.GetInstrumentsAsync(OkxInstrumentType.Swap)

Deserialize JsonSerializationException: Error setting value to 'state' on 'OKX.Api.Models.Public.OkxInstrument'. data: {
  "code": "0",
```

**Comment by burakoner** [comment]
It's fixed on nuget package yesterday. I'll make some extra changes and release new nuget package and commit files to github today. Thanks for feedback

**Comment by burakoner** [comment]
New Release https://github.com/burakoner/OKX.Api/commit/da27018a20640b5e5ba2186311d54b3359569355 and https://www.nuget.org/packages/OKX.Api/1.0.3
