### ISSUE TITLE
Multiple subscription at once, Instument null issue

### ISSUE THREAD

**Issue by kayahasa** [burakoner/OKX.Api#30]
var result = await client.SubscribeToCandlesticksAsync(update =>
            {
                if (update == null)
                {
                    return;
                }
                _futuresCandleService.UpdateSymbol(**update.Instrument**, MapToKlineData(update, interval));
                _priceTickerService.UpdateSymbol(**update.Instrument**, update.Close);

            }, symbolList, interval);
            
            It is good to see multiple subscription at once method support with new release. However,
            in this code, **update.Instrument** is null. 
            Instrument should be set.

**Comment by kayahasa** [comment]
Most probably it is coming as InstrumentId but on the update model it is Instrument. 

So mapping fails.

**Comment by kayahasa** [comment]
Sir,

I have created pull request.

Thanks

**Comment by burakoner** [comment]
Thank you very much for your feedback and pull request. I've merged your request and will release new version in a few hours
