### ISSUE TITLE
api/v5/public/instruments failed because no ApiCredentials were provided.

### ISSUE THREAD

**Issue by kayahasa** [burakoner/OKX.Api#32]
client.PublicData.GetInstrumentsAsync(type);

Request /api/v5/public/instruments failed because no ApiCredentials were provided.

Why this endpoint requires ApiCredentials? I tried via postman it is working. 

It is interesting case. Can you please check ?

**Comment by burakoner** [comment]
It's my mistake. I've forgetten to remove signed flag from this endpoint. I've fixed it on my computer, But as you can see https://github.com/burakoner/OKX.Api/commit/3f621f79f681e60c673eb6db418e02220122de52 I'm prepairing for a big version update. So I cant fix it on release versions. I'll inform you when new version is released

**Comment by burakoner** [comment]
It's a big issue for me. So I've released a hotfix (1.2.5) on nuget. Thank you for your feedback
