### ISSUE TITLE
Candle stick subscription fails.

### ISSUE THREAD

**Issue by kayahasa** [burakoner/OKX.Api#34]
| Trace | OKX Stream | Stream 1 received data: {"event":"error","msg":"channel:index-candle1m,instId:ETH-USDC-SWAP doesn't exist","code":"60018"}

I am using SubscribeToIndexCandlesticksAsync again :) 

But interestingly, i am sending all symbols but only BTC-USD-SWAP price comes. 
All others give error like above.
So right now SubscribeToIndexCandlesticksAsync , Mark Price and all other variations doesnt work. 
For now, i will use single subscription in for loop. Can you please check?

You will see there is no data. (except BTC-USD-SWAP). Its price coming. Others are giving not handled error. Check below. 
This log is being written for all list.

2023/08/06 12:00:05:579 | Warning | OKX Stream | Stream 4 Message not handled: {
12:00:05:592	  "arg": {
12:00:05:592	    "channel": "candle1H",
12:00:05:592	    "instId": "XMR-USDT-SWAP"
12:00:05:592	  },
12:00:05:592	  "data": [
12:00:05:592	    [
12:00:05:592	      "1691312400000",
12:00:05:592	      "160.36",
12:00:05:592	      "160.36",
12:00:05:592	      "160.36",
12:00:05:592	      "160.36",
12:00:05:592	      "0",
12:00:05:592	      "0",
12:00:05:592	      "0",
12:00:05:592	      "0"
12:00:05:592	    ]
12:00:05:592	  ]

**Comment by burakoner** [comment]
Hi. It's related with https://github.com/burakoner/OKX.Api/issues/30 and https://github.com/burakoner/OKX.Api/pull/31
I've fixed this issue for all methods. I'll release new version this night

**Comment by burakoner** [comment]
Version 1.3.0 has been released https://www.nuget.org/packages/OKX.Api/1.3.0
