### ISSUE TITLE
after upgrade, GetAccountBalanceAsync doesnt work

### ISSUE THREAD

**Issue by kayahasa** [burakoner/OKX.Api#35]
TradingAccount.GetAccountBalanceAsync always returns {: No credentials provided for private endpoint } even i have entered credentials. Other endpoints working.

Also,

SubscribeToCandlesticksAsync still doesnt work for multiple subscription at once. Always only BTC-USD-SWAP candle is coming. Others are not coming.

But GetAccountBalanceAsync is mor urgent :(

**Comment by kayahasa** [comment]
GetAccountPositionsAsync also same

**Comment by kayahasa** [comment]
well i think all private endpoints are not working. 

            var client = new OKXRestApiClient();
            client.SetApiCredentials(credentials.ApiKey, credentials.SecretKey, credentials.PassPhrase);
            
            Is this incorrect? It was working before big update.

**Comment by kayahasa** [comment]
/// <summary>
    /// Sets API Credentials
    /// </summary>
    /// <param name="credentials">OkxApiCredentials Object</param>
    public void SetApiCredentials(OkxApiCredentials credentials)
    {
        FundingAccount.SetApiCredentials(credentials);
        OrderBookTrading.SetApiCredentials(credentials);
        BlockTrading.SetApiCredentials(credentials);
        SpreadTrading.SetApiCredentials(credentials);
        PublicData.SetApiCredentials(credentials);
        TradingStatistics.SetApiCredentials(credentials);
        SubAccount.SetApiCredentials(credentials);
        FundingAccount.SetApiCredentials(credentials);
        Status.SetApiCredentials(credentials);
    }
    Here, your forget to add TradingAccount. That is the reason i think.

**Comment by kayahasa** [comment]
https://github.com/burakoner/OKX.Api/pull/36/files

I have created PR, check please

**Comment by burakoner** [comment]
It's my mistake. Thank you for PR. New version will be released in minutes
