### ISSUE TITLE
General Multiple Socket Subscription Issue

### ISSUE THREAD

**Issue by kayahasa** [burakoner/OKX.Api#38]
11:46:21:516	2023/08/12 11:46:21:481 | Warning | OKX WebSocket | WebSocket 1 Message not handled: {
11:46:21:516	  "arg": {
11:46:21:516	    "channel": "positions",
11:46:21:516	    "instType": "SWAP",
11:46:21:516	    "instId": "BTC-USDT-SWAP",
11:46:21:516	    "uid": "446417545424194197"
11:46:21:516	  },
11:46:21:516	  "data": [
11:46:21:516	    {
11:46:21:516	      "adl": "1",
11:46:21:516	      "availPos": "",
11:46:21:516	      "avgPx": "29415.1",
11:46:21:516	      "baseBal": "",
11:46:21:516	      "baseBorrowed": "",
11:46:21:516	      "baseInterest": "",
11:46:21:516	      "bizRefId": "",
11:46:21:516	      "bizRefType": "",
11:46:21:516	      "cTime": "1691740847140",
11:46:21:516	      "ccy": "USDT",
11:46:21:516	      "closeOrderAlgo": [],
11:46:21:516	      "deltaBS": "",
11:46:21:516	      "deltaPA": "",
11:46:21:516	      "gammaBS": "",
11:46:21:516	      "gammaPA": "",
11:46:21:516	      "idxPx": "29397.2",
11:46:21:516	      "imr": "",
11:46:21:516	      "instId": "BTC-USDT-SWAP",
11:46:21:516	      "instType": "SWAP",
11:46:21:516	      "interest": "",
11:46:21:516	      "last": "29399.5",
11:46:21:516	      "lever": "30",
11:46:21:516	      "liab": "",
11:46:21:516	      "liabCcy": "",
11:46:21:516	      "liqPx": "28563.23075506445",
11:46:21:516	      "margin": "9.8050333333333333",
11:46:21:516	      "markPx": "29400",
11:46:21:516	      "mgnMode": "isolated",
11:46:21:516	      "mgnRatio": "7.297077349458313",
11:46:21:516	      "mmr": "1.1760000000000002",
11:46:21:516	      "notionalUsd": "293.8677",
11:46:21:516	      "optVal": "",
11:46:21:516	      "pTime": "1691829979441",
11:46:21:516	      "pendingCloseOrdLiabVal": "",
11:46:21:516	      "pos": "1",
11:46:21:516	      "posCcy": "",
11:46:21:516	      "posId": "607942387314622470",
11:46:21:516	      "posSide": "net",
11:46:21:516	      "quoteBal": "",
11:46:21:516	      "quoteBorrowed": "",
11:46:21:516	      "quoteInterest": "",
11:46:21:516	      "spotInUseAmt": "",
11:46:21:516	      "spotInUseCcy": "",
11:46:21:516	      "thetaBS": "",
11:46:21:516	      "thetaPA": "",
11:46:21:516	      "tradeId": "609235070",
11:46:21:516	      "uTime": "1691740847140",
11:46:21:516	      "upl": "-0.1509999999999855",
11:46:21:516	      "uplLastPx": "-0.1559999999999855",
11:46:21:516	      "uplRatio": "-0.0154002536112396",
11:46:21:516	      "uplRatioLastPx": "-0.0159101957837982",
11:46:21:516	      "usdPx": "",
11:46:21:516	      "vegaBS": "",
11:46:21:516	      "vegaPA": ""
11:46:21:516	    }
11:46:21:516	  ]
11:46:21:516	}

Warning | OKX WebSocket | WebSocket 1 Message not handled: 

This message happening for all Multiple Socket subscriptions. AccoundDataListen, Price Listen, Kline Listen all of them are not working now when you create multiple subscription. 

Can you please check if there are general issue ?

**Comment by kayahasa** [comment]
This example is from SubscribeToPositionUpdatesAsync but as i said, for example indexKline is also giving Message not handled issue.

**Comment by burakoner** [comment]
I tried with total 88 subscriptions, got zero error

**Comment by burakoner** [comment]
I've fixed this issue. Version 1.4.0 has been released. Please check these out https://github.com/burakoner/OKX.Api/commit/a2332273d6d885f3b58a532bc5d63793da3634d8 https://www.nuget.org/packages/OKX.Api/
