### ISSUE TITLE
Error in GetAccountPositionsHistoryAsync

### ISSUE THREAD

**Issue by overstartup** [burakoner/OKX.Api#40]
It seems there is an error when I want to get positions history.
                         
`   var history = api.TradingAccount.GetAccountPositionsHistoryAsync(OkxInstrumentType.Swap, order.Symbol , positionId: order.PositionId.ToString(), limit: 10).Result;`

it was working correctly in this version:
`	<PackageReference Include="OKX.Api" Version="1.1.7" />
`
 this is the error:

```
[27] Deserialize JsonSerializationException: A member with the name 'uly' already exists on 'OKX.Api.Models.TradingAccount.OkxPositionHistory'. Use the JsonPropertyAttribute to specify another name. data: {
  "code": "0",
  "data": [
    {
      "cTime": "1692117524812",
      "ccy": "USDT",
      "closeAvgPx": "29274.5",
      "closeTotalPos": "43",
      "direction": "short",
      "instId": "BTC-USDT-SWAP",
      "instType": "SWAP",
      "lever": "100.0",
      "mgnMode": "cross",
      "openAvgPx": "29332",
      "openMaxPos": "43",
      "pnl": "2.4725",
      "pnlRatio": "0.19603163780172",
      "posId": "611720468101455900",
      "triggerPx": "",
      "type": "2",
      "uTime": "1692118080897",
      "uly": "BTC-USDT"
    }
  ],
  "msg": ""
}
```

**Comment by overstartup** [comment]
@burakoner could you please check this one. Unfortunately, my software doesn't work without this method.

**Comment by vhd41** [comment]
this is a issue in OKX.Api\Models\TradingAccount\OkxPositionHistory.cs
I clone and fix and build a local and use it
    [JsonProperty("uly")]
    public string Underlying { get; set; }

    [JsonProperty("uly")]
    public string Currency { get; set; }
To:
    [JsonProperty("uly")]
    public string Underlying { get; set; } 

    [JsonProperty("ccy")]
    public string Currency { get; set; }

It would be good if @burakoner fix and commit

**Comment by overstartup** [comment]
@vhd41 thanks a lot

**Comment by overstartup** [comment]
@burakoner Please solve these small things. That would be really useful.

**Comment by burakoner** [comment]
I've fixed this issue and will release new version today

**Comment by burakoner** [comment]
Version 1.4.0 has been released. Please check these out https://github.com/burakoner/OKX.Api/commit/a2332273d6d885f3b58a532bc5d63793da3634d8 https://www.nuget.org/packages/OKX.Api/

**Comment by overstartup** [comment]
It works, Thanks
