### ISSUE TITLE
BrokerID

### ISSUE THREAD

**Issue by overstartup** [burakoner/OKX.Api#41]
Could you please add set to brokerid property? 
I know maybe it is different from your business plan, but I need to set it for my software.
`   public string BrokerId { get; }`

I appreciate your effort.

**Comment by burakoner** [comment]
It doesnt effect your orders. If you have a broker account you'll need to create a new class that inherits ClientOptions

**Comment by overstartup** [comment]
Do you mean like this:

```
 public class clientoption : OKXRestApiClientOptions
    {
        public string ApiKey { get; set; }
        public string SecretKey { get; set; }
        public string Passphrase { get; set; }
        public bool DemoTradingService { get; set; }
        public string BrokerId { get; set; }

    }
```
        `    api = new OKXRestApiClient(new clientoption { DemoTradingService = configurationOptions.DemoTradingService, LogLevel = LogLevel.Trace, BrokerId = "test" });`

but it shows 2 brokerID.
![image](https://github.com/burakoner/OKX.Api/assets/56995550/bed38bbd-3f0a-4c53-aa79-217f46cbd238)

**Comment by overstartup** [comment]
@burakoner so there is no solution?

**Comment by burakoner** [comment]
You need to solve this issue yourself. I'm developing OKX wrapper since Jan 26, 2020. I spent my own money and valuable time without getting any profit. If you have your own broker id or dont want to use mine, this is your problem not related with repository

**Comment by overstartup** [comment]
> You need to solve this issue yourself. I'm developing OKX wrapper since Jan 26, 2020. I spent my own money and valuable time without getting any profit. If you have your own broker id or dont want to use mine, this is your problem not related with repository

@burakoner i appreciate your effort.i will sponsor you when my startup gets active.
