### ISSUE TITLE
Public endpoint "GetInstruments" returns response from live API instead from demo trading API

### ISSUE THREAD

**Issue by Radimersky** [burakoner/OKX.Api#42]
Hello, 
I have OKXRestApiClient instantiated like this:
new OKXRestApiClient(new OKXRestApiClientOptions { LogLevel = LogLevel.Debug, **DemoTradingService = true**, DebugMode = true });

Using this client instance, when calling PublicData.GetInstrumentsAsync(OkxInstrumentType.Swap) returns a response from live API instead of demo trading API even when I have DemoTradingService set to true.

The issue is solved when I either add SignPublicRequests = true to the OKXRestApiClientOptions or set the "signed" parameter in GetInstrumentsAsync to true.

I am not sure if this is a bug or if I am missing something significant but I would expect that when using a client with DemoTradingService set to true then every called API endpoint will use DemoTradingService.

**Comment by burakoner** [comment]
I'm not sure how demo service is working. They say some functions dont work in demo service. 
https://www.okx.com/docs-v5/en/#overview-demo-trading-services

But they didnt write anything about your issue (public endpoints, master data). If you really need this function I advice you to contact OKX API department. You can use their telegram group.

**Comment by burakoner** [comment]
Try this

```cs
        OKXApiAddresses.Default = OKXApiAddresses.Demo;
        var api = new OKXRestApiClient(new OKXRestApiClientOptions
        {
            DemoTradingService = true,
        });
```

**Comment by burakoner** [comment]
I'll release a newer version and you wont need to first line anymore.
