### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by vhd41** [burakoner/OKX.Api#43]
var ws = new OKXWebSocketApiClient();
            ws.SetApiCredentials("apiKey","secretKey","passPhrase");

            /* TradingAccount Updates (Private) */
            var res = await ws.TradingAccount.SubscribeToAccountUpdatesAsync((data) =>
            {
                if (data != null)
                {
                    // ... Your logic here
                }
            });
res.Error.Message: Authentication failed: No credentials provided for private endpoint

but the Credentials work fine with Rest Api
Can you help me please?

**Comment by HH-T** [comment]
the same. any solution?

**Comment by burakoner** [comment]
I've fixed this issue and will release new version today. I tested many times and got no error. In your case if error goes on please let me know

**Comment by burakoner** [comment]
Version 1.4.0 has been released. Please check these out https://github.com/burakoner/OKX.Api/commit/a2332273d6d885f3b58a532bc5d63793da3634d8 https://www.nuget.org/packages/OKX.Api/
