### ISSUE TITLE
how to change the default OKXApiadress

### ISSUE THREAD

**Issue by HH-T** [burakoner/OKX.Api#45]
how to change the default Environment Endpoints to AWS Environment Endpoints??

**Comment by burakoner** [comment]
You need to use this code before defining your client instance;

```cs
OKXApiAddresses.Default = OKXApiAddresses.AWS;
```

Then you can create you instance as below 

```cs
var api = new OKXRestApiClient
var wss = new OKXWebSocketApiClient();
```
