### ISSUE TITLE
Convert lever  issue in getorderHistory 

### ISSUE THREAD

**Issue by overstartup** [burakoner/OKX.Api#5]
It gives error when I want to access to orderHistoty

   `  var ordrtHistory = api.Trade.GetOrderHistoryAsync(OkxInstrumentType.Swap, position.Instrument)`

`{: [2] Deserialize JsonReaderException: Could not convert string to integer: 70.0. Path 'data[0].lever', line 1, position 391. Path: data[0].lever, LineNumber: 1, LinePosition: 391  `

**Comment by burakoner** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/21169085/233152263-d53c5ee0-b608-49d5-a7f2-f09b179d8e99.png)

Apparently they changed leverage data type from integer to float. I've fixed it and will release new verison in one hour.

Thanks for feedback

**Comment by burakoner** [comment]
you can check it https://github.com/burakoner/OKX.Api/commit/523cbc108a903ae556c107602e8996808798f0a9 and https://www.nuget.org/packages/OKX.Api/1.0.5
