### ISSUE TITLE
Trading account, GetAccountConfigurationAsync Error

### ISSUE THREAD

**Issue by MihailRom** [burakoner/OKX.Api#53]
Hello!
Please, fix same values in OkxAccountConfiguration model class
https://github.com/burakoner/OKX.Api/blob/master/OKX.Api/Models/TradingAccount/OkxAccountConfiguration.cs

Properties 
`public OkxAccountRoleType? AccountRoleType { get; set; }`
and
`public OkxSpotCopyTradingRole? SpotCopyTradingRole { get; set; }`
have similar value `[JsonProperty("roleType")]`

So, method GetAccountConfigurationAsync returns an error

**Comment by burakoner** [comment]
I've fixed this issue. Please check out Version 1.5.6 at https://github.com/burakoner/OKX.Api/commit/f8b6cccc2c423ca7d4417eb5a3e4b7e6331ac579 and https://www.nuget.org/packages/OKX.Api/1.5.6

Thank you for feedback. Have a great day.
