### ISSUE TITLE
OkxRestApiClient.Public functions hanging

### ISSUE THREAD

**Issue by alekved** [burakoner/OKX.Api#59]
Updated the NuGet OKX.Api package to the latest version.
Now the functions in the OkxRestApiClient.Public space are hanging.
For example.

```
protected OkxRestApiClient _client = null;
OkxRestApiOptions roptions = new OkxRestApiOptions(new OkxApiCredentials(par.Username, par.Password, par.OkexPassPhrase));
roptions.BaseAddress = "https://okx.com";
roptions.DemoTradingService = par.IsDemo;
_client = new OkxRestApiClient(roptions);
RestCallResult<DateTime> wcr = null;
using (CancellationTokenSource cts = new CancellationTokenSource(5000))
{
    wcr = _client.Public.GetServerTimeAsync(cts.Token).Result;
}
```

The last call hangs. The same is with the GetCandlesticksAsync() method.

**Comment by burakoner** [comment]
I've copied your codes to me and worked

![Screenshot 2024-04-04 131028](https://github.com/burakoner/OKX.Api/assets/21169085/f6abbe85-d3a0-410f-a811-6878ac1742ef)

**Comment by alekved** [comment]
Thanks.
It's weird. Probably something is wrong with the rest of my code. But all this stuff worked fine with the older versions of OKX.Api.
I will double-check all.
