### ISSUE TITLE
[Question] Could internal classes be more open for inheritance?

### ISSUE THREAD

**Issue by dnmsk** [burakoner/OKX.Api#60]
Hello!
After Version 1.7.0 some classes such as OkxSocketRequest, OkxSocketOperation became more closed for inheritance.
For example, I'm using custom request to `trades-all` channel with faster message matching.

**Comment by burakoner** [comment]
You're right. I'll edit all sealed or internal classes except converters

**Comment by burakoner** [comment]
I'm working on all classes for inheritance including converters as well

**Comment by burakoner** [comment]
Version 2.0.3 released
