### ISSUE TITLE
AttachedAlgoOrders Not Working

### ISSUE THREAD

**Issue by javedwahid** [burakoner/OKX.Api#64]
When I create an new OkxTradeOrderPlaceRequest() and populate the AttachedAlgoOrders property with an OkxTradeOrderPlaceAttachedAlgoRequest.  

The Order doesn't go through and all that is returned is the OkxTradeOrderPlaceResponse that says Success = True.

I populated the TakeProfitTriggerPrice, TakeProfitOrderPrice and Size
and other variations of properties and none of them actually placed an order.

**Comment by burakoner** [comment]
I'm not sure if I understand right. OKX Place Order endpoint returns a response as below

```json
{
  "code": "0",
  "msg": "",
  "data": [
    {
      "clOrdId": "oktswap6",
      "ordId": "312269865356374016",
      "tag": "",
      "ts":"1695190491421",
      "sCode": "0",
      "sMsg": ""
    }
  ],
  "inTime": "1695190491421339",
  "outTime": "1695190491423240"
}
```

OKX.Api shows you data array part of this message only. If you mean "why this reponse model is limited?" this is all OKX response. If you mean you cant see any part of "data" please enable rawresponse and send me raw data as below.
```csharp
var api = new OkxRestApiClient(new OkxRestApiOptions
{
  RawResponse = true,
});

var trade = await api.Trading.PlaceOrderAsync(...)
// send me trade.Raw property value
```

Have a great day

**Comment by javedwahid** [comment]
When I would call the method, it would return, but without providing the Order Id.  Then when I checked my OKX account, the order wasn't showing there.

I will do the RawResponse and get that information for you along with a screenshot.

**Comment by burakoner** [comment]
Does your problem persist?

**Comment by javedwahid** [comment]
Sorry, I haven't checked yet.  I had reverted back to v2.4.8 at that point and have been busy with developing.  There's several changes that I had noticed regarding class names and parameters, so it's not just as easy and upgrading the Nuget Package.  Especially if there's other things that end up not working;.

**Comment by burakoner** [comment]
Please let me know if you need help

**Comment by burakoner** [comment]
I tried to place an order with attached order and got error below. If you are a copy (lead) trader you may not be able to use attached algo orders. I tried with OKB-USDT symbol not even in my copy trader portfolio and got error. I think it is a rule of OKX.

![Screenshot 2024-10-08 105741](https://github.com/user-attachments/assets/4520e1ab-e8b2-4b7c-9530-34b7caae5440)
