### ISSUE TITLE
ws.Trading.SubscribeToOrderUpdatesAsync doesn't seem to be working in v2.6.7

### ISSUE THREAD

**Issue by javedwahid** [burakoner/OKX.Api#65]
I upgraded to v2.6.7 and ws.Trading.SubscribeToOrderUpdatesAsync() seems to have stopped working.  It connects and says that it has a StreamId, but when orders are updated, nothing comes through.

**Comment by burakoner** [comment]
Checking...

**Comment by burakoner** [comment]
I've fixed this issue and will release tonight

**Comment by javedwahid** [comment]
Thank You,

**Comment by burakoner** [comment]
New version has been released and issue fixed. Thanks for feedback. Regards.
