### ISSUE TITLE
ws.Account.SubscribeToAccountUpdatesAsync doesn't work in v2.6.7

### ISSUE THREAD

**Issue by javedwahid** [burakoner/OKX.Api#66]
After upgrading to v2.6.7.  It seems that ws.Account.SubscribeToAccountUpdatesAsync() isn't working either.

**Comment by burakoner** [comment]
I've fixed this issue and will release tonight

**Comment by burakoner** [comment]
New version has been released and issue fixed. Thanks for feedback. Regards.
