### ISSUE TITLE
GetInstrumentsAsync missing variables

### ISSUE THREAD

**Issue by brightb1ue** [burakoner/OKX.Api#7]
{"alias":"","baseCcy":"","category":"1","ctMult":"1","ctType":"inverse","ctVal":"100","ctValCcy":"USD","expTime":"","instFamily":"BTC-USD","instId":"BTC-USD-SWAP","instType":"SWAP","lever":"125","listTime":"1611916828000","lotSz":"1","maxIcebergSz":"100000000.0000000000000000","maxLmtSz":"100000000","maxMktSz":"10000","maxStopSz":"10000","maxTriggerSz":"100000000.0000000000000000","maxTwapSz":"100000000.0000000000000000","minSz":"1","optType":"","quoteCcy":"","settleCcy":"BTC","state":"live","stk":"","tickSz":"0.1","uly":"BTC-USD"}

Some variable are missing when using GetInstrumentsAsync.
maxIcebergSz, maxLmtSz, maxMktSz, maxStopSz, maxTriggerSz, maxTwapSz

Could you add those variables?

**Comment by burakoner** [comment]
Fixed in https://github.com/burakoner/OKX.Api/commit/7ce8234eeda11ba61241da68d2dce5efdf1e7796 and https://www.nuget.org/packages/OKX.Api/1.0.6
