### ISSUE TITLE
OkxTradeOptionsPriceType

### ISSUE THREAD

**Issue by javedwahid** [burakoner/OKX.Api#74]
Hi,

Since I upgraded to the latest version.  I seem to be getting this message show up a lot while testing things: "2024/12/22 17:59:32:683 | Warning | Received null enum value, but property type is not a nullable enum. EnumType: OkxTradeOptionsPriceType. If you think OkxTradeOptionsPriceType should be nullable please open an issue on the Github repo"

I was wondering if there was a way to turn it off so I don't see this message?

Thanks,

Javed

**Comment by burakoner** [comment]
Hi

No, there is not an option to turn off this warnings. I've fixed this issue on v5.4.1223. Please update your nuget package.

Thanks for sharing issue
