### ISSUE TITLE
restClient.Algo.GetOpenOrdersAsync - JsonSerializationException

### ISSUE THREAD

**Issue by SiberShami** [burakoner/OKX.Api#75]
Happy New Year, Friends! 
I encountered an error of receiving TP/SL Orders. RestCallResult displays the following message: 

_restClient.Algo.GetOpenOrdersAsync(Conditional): Error.Code: , Error.Message: [1] Deserialize JsonSerializationException: Error converting value “” to type 'System.Boolean'. Path 'data[0].isTradeBorrowMode'

Regards and best wishes, Sib

**Comment by burakoner** [comment]
Hi. I've fixed this issue in v5.4.1231. Thanks for feedback.

**Comment by SiberShami** [comment]
Thank you for such a lightning fast response! )
I updated and the following warning popped up about 

Error converting value “” to type 'System.Int64'. Path 'data[0].linkedOrd.ordId'.

The parser gives in bits and pieces, instead of all the obstacles )  
I will describe in the following issue

**Comment by burakoner** [comment]
I'll fix this error tonight

**Comment by burakoner** [comment]
v5.5.101 has been released
