### ISSUE TITLE
Algo.GetOpenOrdersAsync - JsonSerializationException

### ISSUE THREAD

**Issue by SiberShami** [burakoner/OKX.Api#76]
Happy New Year again! )
Moving on) 

_restClient.Algo.GetOpenOrdersAsync(Conditional): Error.Code: , Error.Message: [1] Deserialize JsonSerializationException: Error converting value “” to type 'System.Int64'. Path 'data[0].linkedOrd.ordId'

**Comment by burakoner** [comment]
Hi. I'll fix this issue tonight

**Comment by burakoner** [comment]
v5.5.101 has been released

**Comment by SiberShami** [comment]
Thank you very much! You are very cool!
