### ISSUE TITLE
UnitConvert  Error

### ISSUE THREAD

**Issue by overstartup** [burakoner/OKX.Api#8]
I had this issue with the previous library too. Here are my parameters:
`   var r=    api.MarketData.UnitConvertAsync(OkxConvertType.CurrencyToContract,  OkxConvertUnit.Usdt, "DOT-USDT-SWAP", 5.642M, 239).Result;`

`Sending GET request to https://www.okx.com/api/v5/public/convert-contract-coin?instId=DOT-USDT-SWAP&px=5.642&sz=239&type=1&unit=0 `

it gives this error:
`OKX RestApi | [91] Error received in 252ms: {"code":"51000","data":[],"msg":"Parameter unit  error"}`

i want to set my order size, for example I want to place order by 10=USDT, leverage =50 and market price is 5.642.

How can I convert the 10 USDT to contract?

**Comment by burakoner** [comment]
Hi

There is problem is related with "unit" parameter conversation. unit is "0" in your request, but it must be coin or usds. I've fixed it on my side. I've tested It works fine now. I'm working on a very big update. OKX Api has changed a lot. I think it will take around a week. But I'll release a version today.

Thanks for feedback.

**Comment by burakoner** [comment]
Check this out

https://github.com/burakoner/OKX.Api/commit/e305535488f05c27df5ddd0efb50fbfac7ead47a and https://www.nuget.org/packages/OKX.Api/1.1.0

**Comment by overstartup** [comment]
Thanks a lot , i t works fine now. But still I have issue in calculating the order Quantity. 

i want to trade btc-usdt :
price : 2880
levrage : 50
amont usdt to place : 20 usdt
Quantity??
```
           var orderResult = await api.Trade.PlaceOrderAsync( Symbol, trademode,
                                                       orderSide, positionSide,
                                                       OkxOrderType.MarketOrder, preOrder.Quantity, currency: "USDT");
```


do you have any idea how can i reach the correct number in this example?
