### ISSUE TITLE
add request header for demo version

### ISSUE THREAD

**Issue by overstartup** [burakoner/OKX.Api#9]
i had chat with okx api developers. it seems we missed the header to get demo data. They asked me to change this header:
`Add to request header。x-simulated-trading: 1`

The check was for this endpoint, but I don't know if you need to add it for others too.
`api.PublicData.GetInstrumentsAsync(...);`

**Comment by burakoner** [comment]
You can simply set DemoTradingService=true in OkxRestApiClientOptions

**Comment by overstartup** [comment]
it doesn't solve the issue. Because it still set wrong order size. The support told me it needs the header to return correct data for demo version.

**Comment by burakoner** [comment]
DemoTradingService=true adds header parameter
